/*!
 * Copyright (c) 2024 PLANKA Software GmbH
 * Licensed under the Fair Use License: https://github.com/plankanban/planka/blob/master/LICENSE.md
 */

import { ORM } from 'redux-orm';

import {
  Activity,
  Attachment,
  BackgroundImage,
  BaseCustomFieldGroup,
  Board,
  BoardLink,
  BoardMembership,
  BoardRelease,
  BoardTeam,
  Card,
  CardDependency,
  Comment,
  CustomField,
  CustomFieldGroup,
  CustomFieldValue,
  Label,
  List,
  Notification,
  NotificationService,
  Project,
  ProjectCategory,
  ProjectCategoryAssignment,
  ProjectManager,
  ProjectTeam,
  ReleaseCard,
  Report,
  ReportPhase,
  ReportPhaseMembership,
  ProjectProfile,
  ProjectProfileSection,
  ProjectProfileField,
  ProjectProfileData,
  ProjectHistory,
  Task,
  TaskList,
  Team,
  TeamMembership,
  User,
  Webhook,
  Space,
  Folder,
  File,
  Permission,
  ShareLink,
} from './models';

const orm = new ORM({
  stateSelector: (state) => state.orm,
});

orm.register(
  Webhook,
  User,
  Space,
  Folder,
  File,
  Permission,
  ShareLink,
  Project,
  ProjectCategory,
  ProjectCategoryAssignment,
  ProjectManager,
  ProjectTeam,
  Team,
  TeamMembership,
  BackgroundImage,
  BaseCustomFieldGroup,
  Board,
  BoardLink,
  BoardMembership,
  BoardRelease,
  BoardTeam,
  Label,
  List,
  Card,
  ReleaseCard,
  CardDependency,
  TaskList,
  Task,
  Attachment,
  CustomFieldGroup,
  CustomField,
  CustomFieldValue,
  Comment,
  Activity,
  Notification,
  NotificationService,
  Report,
  ReportPhase,
  ReportPhaseMembership,
  ProjectProfile,
  ProjectProfileSection,
  ProjectProfileField,
  ProjectProfileData,
  ProjectHistory,
);

export default orm;
