/*!
 * Copyright (c) 2024 PLANKA Software GmbH
 * Licensed under the Fair Use License: https://github.com/plankanban/planka/blob/master/LICENSE.md
 */

const ADMINISTRATION = 'ADMINISTRATION';
const USER_SETTINGS = 'USER_SETTINGS';
const ADD_PROJECT = 'ADD_PROJECT';
const PROJECT_SETTINGS = 'PROJECT_SETTINGS';
const BOARD_SETTINGS = 'BOARD_SETTINGS';
const BOARD_ACTIVITIES = 'BOARD_ACTIVITIES';
const BOARD_VERSIONS = 'BOARD_VERSIONS';
const BOARD_RELEASES = 'BOARD_RELEASES';
const ADD_BOARD_RELEASE = 'ADD_BOARD_RELEASE';
const EDIT_BOARD_RELEASE = 'EDIT_BOARD_RELEASE';

export default {
  ADMINISTRATION,
  USER_SETTINGS,
  ADD_PROJECT,
  PROJECT_SETTINGS,
  BOARD_SETTINGS,
  BOARD_ACTIVITIES,
  BOARD_VERSIONS,
  BOARD_RELEASES,
  ADD_BOARD_RELEASE,
  EDIT_BOARD_RELEASE,
};
